spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}:5432/${DATABASE_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI} # https://login.microsoftonline.com/${TENANT_ID}/v2.0
          audience: ${JWT_AUDIENCE} # AD_CLIENT_ID
server:
  port: ${SERVER_PORT}
springdoc:
  swagger-ui:
    oauth:
      client-id: ${SWAGGER_AD_CLIENT_ID}
      use-pkce-with-authorization-code-grant: true
archiwork-commons:
  oauth-flow:
    authorizationUrl: ${AUTHORIZATION_URL} # https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/authorize
    tokenUrl: ${TOKEN_URL} # https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
    scope: ${AD_SCOPE}