spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}:5432/${DATABASE_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
commands:
  api:
    base-url: ${EVENTS_API_BASE_URL}
    client-id: ${AD_CLIENT_ID}
    client-secret: ${AD_CLIENT_SECRET}
    token-uri: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
    scopes:
      - ${EVENTS_APP_IDENTIFIER_URI}/access_as_user
polling:
  limit: 1000