spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aggregator
    driver-class-name: org.postgresql.Driver
    username: pgadmin
    password: pgadmin
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
commands:
  api:
    base-url: http://localhost:8080
polling:
  limit: 1000