spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aggregator
    driver-class-name: org.postgresql.Driver
    username: pgadmin
    password: pgadmin
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/events-realm
          audience: aggregator-client
springdoc:
  swagger-ui:
    oauth:
      client-id: swagger-aggregator-client
      use-pkce-with-authorization-code-grant: true
archiwork-commons:
  oauth-flow:
    authorizationUrl: http://localhost:8081/realms/events-realm/protocol/openid-connect/auth
    tokenUrl: http://localhost:8081/realms/events-realm/protocol/openid-connect/token
    scope: aggregator_api_user
server:
  port: 8082
commands:
  api:
    base-url: http://localhost:8080
    client-id: aggregator-client
    client-secret: aggregator-secret
    token-uri: http://localhost:8081/realms/events-realm/protocol/openid-connect/token
    scopes:
      - events_api_user
polling:
  limit: 1000