spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}:5432/${DATABASE_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
commands:
  api:
    base-url: https://archiwork-events-wa.azurewebsites.net