spring:
  config:
    import: "classpath:application-cloud-common.yaml"
commands:
  api:
    base-url: ${EVENTS_API_BASE_URL}
    client-id: ${AD_CLIENT_ID}
    client-secret: ${AD_CLIENT_SECRET}
    token-uri: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
    scopes:
      - ${EVENTS_APP_SCOPE}
polling:
  limit: 1000