spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/aggregator
    driver-class-name: org.postgresql.Driver
    username: pgadmin
    password: pgadmin
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
commands:
  api:
    base-url: http://localhost:8080
    client-id: aggregator-client
    client-secret: aggregator-secret
    token-uri: http://localhost:8081/realms/events-realm/protocol/openid-connect/token
    scopes:
      - events_api_user
polling:
  limit: 1000