spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}:5432/${DATABASE_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${TENANT_ID}/v2.0
          audience: ${APP_IDENTIFIER_URI}
springdoc:
  swagger-ui:
    oauth:
      client-id: ${SWAGGER_AD_CLIENT_ID}
      use-pkce-with-authorization-code-grant: true
