spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/events-realm
          audience: events-api
springdoc:
  swagger-ui:
    oauth:
      client-id: swagger-ui-client
      use-pkce-with-authorization-code-grant: true
events:
  oauth-flow:
    authorizationUrl: https://localhost:8081/authorize
    tokenUrl: https://localhost:8081/oauth2/v2.0/token
    scope: EVENTS_APP/access_as_user