spring:
  config:
    import: "classpath:application-common.yaml"
  datasource:
    url: jdbc:postgresql://localhost:5432/events
  security:
    oauth2:
      resourceserver:
        jwt:
          audience: events-api
springdoc:
  swagger-ui:
    oauth:
      client-id: swagger-ui-client
archiwork-commons:
  oauth-flow:
    scope: events_api_user