name: Build, Terraform, and Deploy

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  terraform-build-deploy:
    name: Terraform Plan & Apply, Build, Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Show Terraform version
        run: terraform version

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init -backend-config=${{ vars.TF_BACKEND_CONFIG }}
        working-directory: infra

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var-file=${{ vars.TF_VARS_CONFIG }}
        working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=${{ vars.TF_VARS_CONFIG }} tfplan
        working-directory: infra

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: "events-app"
          package: "events/build/libs/*.jar"

      - name: Check App Health
        run: | #TODO app address
          for i in {1..10}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://events-app.azurewebsites.net/actuator/health) 
            echo "Health check HTTP status: $STATUS"
            if [ "$STATUS" -eq 200 ]; then
              echo "✅ App is healthy!"
              exit 0
            fi
            echo "Waiting for app to become healthy... ($i/10)"
            sleep 10
          done
          echo "❌ App failed to become healthy in time"
          exit 1